output_dir = "tmp"

# Ignore Patterns
#
# This uses the same spec as .gitignore
#
# The application already has a list of known patterns that it uses to exclude/ignore files.
# Add your project specific patterns here; less noise makes Agents work smarter!
ignore = [
    "tools",
    "tests",
    "build",
    "docs",
    "libraries",
    "firmware/configs",
    "README.md",
    "CONTRIBUTING.md"
]

[property_mapper_agent]
litellm_provider = "prov-1"
# The extra context is a list of file paths
# (Markdown, text) that could enhance PropertyMapper agents
# These would be appended after the system prompt of the agent
extra_context = []

# contains the list of device properties to not even consider
# e.g. ["PID-11", "PID-231" ..]
excluded_properties = []

# LiteLLM Providers
# In the examples below prov-1, prov-2 are the names that
# need to be used as the values for "litellm_provider" for various agent configurations

[litellm_provider.prov-1]
model_name = "ollama_chat/devstral-small-2:24b"
provider_args = { api_key = "ollama", api_base = "http://host.docker.internal:11434" }

[litellm_provider.prov-2]
model_name = "ollama_chat/kimi-k2.5:cloud"
provider_args = { api_key = "ollama", api_base = "http://host.docker.internal:11434" }

[litellm_provider.gh-copilot-sonnet]
# for github copilit models, you would be ask to verify
# the code and token will be store locally
model_name = "github_copilot/claude-sonnet-4.6"

[litellm_provider.azure-openai]
model_name = "azure/gpt-4.1"
# You could supply your keys here but wouldn't recommend it
# as you would want the config to be source controlled as well
#
# Instead use environment variable corresponding to your model
# AZURE_API_KEY & AZURE_API_BASE for OpenAI endpoints
# See - https://docs.litellm.ai/docs/providers/azure/
provider_args = { api_key = "<YOUR_KEY>", api_base = "", api_version = "2024-12-01-preview"}

[litellm_provider.azure-ai]
model_name = "azure_ai/gpt-5.3-codex"
# You could supply your keys here but wouldn't recommend it
# as you would want the config to be source controlled as well
#
# Instead use environment variable corresponding to your model
# AZURE_AI_API_KEY & AZURE_AI_API_BASE
# See - https://docs.litellm.ai/docs/providers/azure_ai
provider_args = { api_key = "<YOUR_KEY>", api_base = "", api_version = "2025-04-01-preview"}
